mozilla/code-review

- .taskcluster.yml
- bot/Dockerfile
- bot/code_review_bot/config.py
- bot/taskcluster-hook.json
- bot/tests/mock_taskcluster.py
- bot/tests/test_remote.py
- frontend/package.json
> Taskcluster CI/CD

- bot/code_review_bot/tasks/base.py
> Don't fail if the latest coverage task was not correctly indexed

- bot/code_review_bot/config.py
- bot/code_review_bot/revisions.py
- bot/code_review_bot/tasks/base.py
- bot/code_review_bot/tasks/coverity.py
- bot/code_review_bot/workflow.py
- bot/tests/test_remote.py
Needed to support https://github.com/mozilla/release-services/pull/2180 and [Bug 1559095](https://bugzilla.mozilla.org/show_bug.cgi?id=1559095)
Could also be used to update the variable name on MC
:warning: The `reliability` key in Coverity payload is now optional.
> bot: Support NSS tasks.

- bot/code_review_bot/revisions.py
- bot/code_review_bot/workflow.py
- bot/tests/test_workflow.py
- frontend/src/Choice.vue
- frontend/src/Tasks.vue
- frontend/src/store.js
> Filter by repositories

- .isort.cfg
- bot/code_review_bot/__init__.py
- bot/code_review_bot/cli.py
- bot/code_review_bot/report/phabricator.py
- bot/code_review_bot/revisions.py
- bot/code_review_bot/stats.py
- bot/code_review_bot/workflow.py
- bot/requirements.txt
- bot/tests/conftest.py
- bot/tests/test_clang.py
- bot/tests/test_remote.py
- bot/tests/test_stats.py
> InfluxDb support

- .isort.cfg
- bot/code_review_bot/config.py
- bot/code_review_bot/revisions.py
- bot/code_review_bot/tasks/clang_tidy.py
- bot/requirements.txt
- bot/tests/conftest.py
- bot/tests/test_clang.py
> Remove clang checks & remote config load

- events/docker/bootstrap.sh
Fix [Sentry issue](https://sentry.prod.mozaws.net/operations/code-review-events/issues/6359135/)
> events: Fix the mercurial hgrc path in Dockerfile

- tools/code_review_tools/log.py
Now that we control Sentry, we can do cool stuff like:
- using package version to detect if a failure still occurs after a deployment
- adding extra info like a Taskcluster task id.
On this [test Sentry issue](https://sentry.prod.mozaws.net/operations/code-review-bot/issues/6359397) you can view the release `1.0.3` and the taskcluster task id `testBastien`
> tools: Add release & taskcluster infos in Sentry.

- bot/code_review_bot/tasks/base.py
- bot/code_review_bot/tasks/lint.py
- bot/tests/test_artifacts.py
> bot: Skip completed mozlint tasks without warning

- bot/code_review_bot/report/base.py
- bot/tests/test_reporter_phabricator.py
> bot: Better zero coverage issues comment

- bot/code_review_bot/tasks/lint.py
Avoid [that dumb issue](https://tools.taskcluster.net/groups/SPlYsuKtS1iGuIpleWy3IA/tasks/SPlYsuKtS1iGuIpleWy3IA/runs/0/logs/public%2Flogs%2Flive.log)
> Remove remaining is_third_party call

- events/requirements.txt
> events: Use libmozevent 1.0.2

- .flake8
- bot/code_review_bot/__init__.py
- bot/tests/test_hash.py
> Use positive integers for line & nb_lines

- bot/code_review_bot/__init__.py
- bot/code_review_bot/tasks/lint.py
- bot/tests/fixtures/mozlint_license_no_check.json
- bot/tests/test_lint.py
> Use default value for check

- bot/code_review_bot/report/__init__.py
- bot/code_review_bot/report/backend.py
- bot/code_review_bot/revisions.py
- bot/tests/conftest.py
- bot/tests/mocks/phabricator_revision_search.json
- bot/tests/test_reporter_backend.py
- bot/tests/test_reporter_debug.py
> Publish issues in backend

- bot/code_review_bot/tasks/default.py
- bot/code_review_bot/workflow.py
- bot/tests/conftest.py
- bot/tests/test_default.py
- docs/analysis_format.md
Fixes #153
@sylvestre if you can take a look at [the updated format in the docs](https://github.com/La0/code-review/blob/165f8203a2bf20d5ed44ad4f0e9387c07eea9051/docs/analysis_format.md)
> Add a default task parser

- bot/code_review_bot/__init__.py
- bot/code_review_bot/report/phabricator.py
- bot/code_review_bot/tasks/clang_format.py
- bot/code_review_bot/tasks/clang_tidy.py
- bot/code_review_bot/tasks/coverage.py
- bot/code_review_bot/tasks/coverity.py
- bot/code_review_bot/tasks/default.py
- bot/code_review_bot/tasks/infer.py
- bot/code_review_bot/tasks/lint.py
- bot/code_review_bot/workflow.py
- bot/tests/test_remote.py
- bot/tests/test_reporter_phabricator.py
> Remove ANALYZER from Task & Issue

- bot/code_review_bot/workflow.py
> Use default task parser first

- bot/code_review_bot/report/mail.py
> Fix linting bug after black update

- backend/code_review_backend/app/settings.py
- backend/requirements.txt
Refs #187 
An easy one @marco-c :smile:
> Add cors headers

- backend/code_review_backend/app/urls.py
- backend/code_review_backend/issues/api.py
- backend/code_review_backend/issues/serializers.py
- backend/code_review_backend/issues/tests/test_stats.py
> Add analyzer checks stats API

- backend/code_review_backend/issues/api.py
- backend/code_review_backend/issues/serializers.py
- backend/code_review_backend/issues/tests/test_repository.py
> List all repositories available through repository

- bot/code_review_bot/backend.py
- bot/code_review_bot/report/__init__.py
- bot/code_review_bot/revisions.py
- bot/code_review_bot/workflow.py
- bot/tests/conftest.py
- bot/tests/test_backend.py
- bot/tests/test_default.py
- bot/tests/test_remote.py
> Always store revision & diff on backend

- tools/requirements.txt
Same as https://github.com/mozilla/code-coverage/pull/261
> Limit async-timeout version

- backend/code_review_backend/app/settings.py
Testing now as I just got the domains + SSL certs...
> Use Heroku SSL headers to build https:// urls

- .taskcluster.yml
- backend/code_review_backend/issues/management/commands/load_issues.py
- bot/README.md
- bot/code_review_bot/retrigger.py
- docs/new_repository.md
- events/tests/conftest.py
- frontend/src/Check.vue
- frontend/src/Task.vue
- frontend/src/Tasks.vue
- frontend/src/store.js
- tools/code_review_tools/taskcluster.py
I stole some url changes from @imbstack and fixed some pre-commit issues.
Sorry i inadvertently closed the previous PR :cry:
> Taskcluster community migration

- tools/code_review_tools/taskcluster.py
Let's avoid old time shenanigans as we are using new TC urls
> simplify taskcluster proxy setup

- backend/code_review_backend/issues/api.py
- backend/code_review_backend/issues/tests/test_diff.py
Better display in the frontend (otherwise we always see the same old diffs)
> Order diffs from newer to older

- backend/code_review_backend/issues/api.py
- backend/code_review_backend/issues/tests/test_diff.py
* By revision's repository
* By search terms, looking up in:
* revision id
* diff id
* bugzilla id
* revision title
* By issues on the diff
* any issues
* new issues
* no issues at all
> Issues filters

- events/code_review_events/workflow.py
- events/tests/test_workflow.py
> Use taskcluster community instance for risk analysis

- tools/code_review_tools/taskcluster.py
To avoid [Bug 1595838](https://bugzilla.mozilla.org/show_bug.cgi?id=1595838) which prevents us from using blob upload for clang-format patches
> Use S3 artifact for text/plain patches

- bot/code_review_bot/__init__.py
- bot/code_review_bot/report/base.py
- bot/code_review_bot/report/phabricator.py
- bot/code_review_bot/revisions.py
- bot/tests/test_hash.py
- bot/tests/test_reporter_phabricator.py
- bot/tests/test_revisions.py
> Support full file reporting on Phabricator

- bot/tools/test_validator.py
- bot/tools/validator.py
- docs/analysis_format.md
> Add validator for default format

- events/code_review_events/workflow.py
For now, this will just trigger the hook (randomly for a configurable subset of revisions), without acting on the result.
> events: Trigger bugbug's test selection hook on a subset of reviews

- events/code_review_events/cli.py
- events/code_review_events/workflow.py
- events/requirements.txt
- events/tests/conftest.py
- events/tests/fixtures/phabricator/revision-search-98765.json
- events/tests/fixtures/phabricator/user-search-baduser123.json
- events/tests/test_workflow.py
> Support user black list

- bot/code_review_bot/report/base.py
- bot/tests/test_reporter_phabricator.py
> Do not say when 0 issues found on task failures

- events/code_review_events/workflow.py
- tools/code_review_tools/heroku.py
> Split workloads.

- bot/code_review_bot/tasks/clang_format.py
- bot/tests/test_clang.py
> Fix empty patch detection failing on newlines

- events/code_review_events/bugbug_utils.py
> Use taskcluster.helper for connecting to the community Taskcluster deployment

- events/code_review_events/workflow.py
- events/tests/test_workflow.py
We can do this once a new version of libmozevent with https://github.com/mozilla/libmozevent/commit/3591431fb4a1d04e8e400b99b695c165abbc70c1 is released.
> Use bus.dispatch instead of a custom implementation

- .taskcluster.yml
[Bug 1594660](https://bugzilla.mozilla.org/show_bug.cgi?id=1594660#c5)
> setup: Upgrade S3 bucket for frontend deploy, 

- events/code_review_events/bugbug_utils.py
>  Send an email when test selection is triggered for a given try push

- events/tests/test_bugbug_utils.py
This doesn't affect anything for now, but I want to do it just so we don't rely on wrong assumptions in the future.
> Make pulse payload what it should be with aioamqp 0.14.0

- events/code_review_events/__init__.py
- events/code_review_events/bugbug_utils.py
- events/code_review_events/cli.py
- events/code_review_events/workflow.py
- events/tests/conftest.py
- events/tests/test_bugbug_utils.py
> Support monitoring tasks in the community Taskcluster deployment

- bot/code_review_bot/cli.py
- bot/code_review_bot/workflow.py
- bot/tests/conftest.py
- bot/tests/test_remote.py
> Support ignoring some task failures

- frontend/src/Tasks.vue
- frontend/src/store.js
> Support repository urls

- events/code_review_events/__init__.py
> Enforce community TC url

- events/code_review_events/workflow.py
> Lower log level for autoland

- backend/code_review_backend/issues/api.py
As we now have the repo information on diffs too.
> Filter diffs on their own repo too.

- bot/code_review_bot/workflow.py
- bot/taskcluster-hook.json
- bot/tests/test_workflow.py
Refs #333
[The hook definition will need to be updated in ci-configuration](https://phabricator.services.mozilla.com/D57289)
> Remove relman.tasks route usage,

- integration/run.py
- integration/tests/conftest.py
- integration/tests/test_workflow.py
To avoid [current bug on testing](https://community-tc.services.mozilla.com/tasks/B0ObDaI_QFCdAvB6x06CAA/runs/0/logs/https%3A%2F%2Fcommunity-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FB0ObDaI_QFCdAvB6x06CAA%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log)
> Add unit test & fix url parsing

- backend/README.md
- backend/code_review_backend/app/settings.py
I needed a dump from real data to test devs for #320 . Works pretty well !
> Add documentation & support for local postgres database.

- .isort.cfg
- events/code_review_events/bugbug_utils.py
- events/code_review_events/workflow.py
- events/requirements.txt
- events/tests/conftest.py
- events/tests/fixtures/treeherder/jobdetail.json
- events/tests/test_bugbug_utils.py
- events/tests/test_workflow.py
> events: Add a URL to Treeherder in the Phabricator test results

- events/code_review_events/bugbug_utils.py
- events/tests/fixtures/phabricator/user-search-ehsan-tnguyen.json
- events/tests/test_bugbug_utils.py
> Trigger risk analysis for specific authors too

- integration/run.py
- integration/tests/test_workflow.py
Works again : https://phabricator-dev.allizom.org/D1647
> integration: do not use --no-arc anymore

- .taskcluster.yml
Depends on https://github.com/mozilla/community-tc-config/pull/180
> setup: Publish a Github release using task-boot

- bot/code_review_bot/__init__.py
- bot/code_review_bot/cli.py
- bot/code_review_bot/config.py
- bot/tests/conftest.py
- bot/tests/test_issues.py
- bot/tests/test_workflow.py
> Use backend publishable status on issues,

- tools/docker/bootstrap-mercurial.sh
> tools: Use Mercurial with Python 3

- events/code_review_events/bugbug_utils.py
- events/code_review_events/workflow.py
- events/requirements.txt
- events/tests/test_bugbug_utils.py
> events: Update to libmozevent 1.1.2

- backend/code_review_backend/issues/api.py
- backend/code_review_backend/issues/serializers.py
- backend/code_review_backend/issues/tests/test_diff.py
- frontend/src/Diffs.vue
> Display errors & warnings on the frontend

- events/requirements.txt
- tools/requirements.txt
> Freeze library versions in tools

- events/docker/Dockerfile
> Revert Python to 3.7 in docker image

- backend/code_review_backend/issues/api.py
- backend/code_review_backend/issues/tests/test_stats.py
- frontend/src/Check.vue
- frontend/src/store.js
Fixes #445 
Requested by @sylvestre
> UX enhancements to list issues in a check

- .mergify.yml
> Automate squash merge when a PR is approved & CI is green

- tools/requirements.txt
Should fix [this issue](https://community-tc.services.mozilla.com/tasks/ZQD3iy3fTQagBaDWelclvg/runs/0/logs/https%3A%2F%2Fcommunity-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FZQD3iy3fTQagBaDWelclvg%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log)
> tools: Limit idna version to fix docker build.

- events/code_review_events/workflow.py
- events/tests/test_workflow.py
While working on #461 I did not want to copy yet another time the ssh key shared between projects.
So i implemented a default ssh key mechanism, stored at the same level as the repositories.
> Use a default ssh key for projects.

- bot/code_review_bot/report/base.py
- bot/code_review_bot/report/phabricator.py
- bot/tests/test_reporter_phabricator.py
- events/code_review_events/bugbug_utils.py
- tools/code_review_tools/treeherder.py
> Add frontend & treeherder links in the summary comment

- .mergify.yml
And auto merge contributors' PRs
> Enable mergify to auto merge Dependabot PRs

- backend/code_review_backend/app/settings.py
Fixes #484 & https://bugzilla.mozilla.org/show_bug.cgi?id=1616817
> Check SECRET_KEY is always set on Heroku.

- .taskcluster.yml
> Build bot docker image with DinD on firefox-ci Taskcluster instance

- .taskcluster.yml
> Setup Taskcluster route to find bot DinD build on firefox-ci.

- bot/code_review_bot/workflow.py
- bot/tests/test_workflow.py
> Support all dependant tasks by default

- .taskcluster.yml
- Only test & build on Firefox CI
- No more bot build with img on Community CI
- No more bot push on Community CI
> Do not build or ship the bot from Community TC

- .taskcluster.yml
This depends on https://phabricator.services.mozilla.com/D64152 landing for PRs to work.
> Use standard indexes.

- bot/requirements-dev.txt
As the breaking has been reverted https://github.com/pypa/virtualenv/issues/1669#issuecomment-591508506
> Unpin virtualenv

- bot/code_review_bot/report/base.py
- bot/tests/test_reporter_phabricator.py
See https://bugzilla.mozilla.org/show_bug.cgi?id=1621322#c1
> Update mozlint instructions

- bot/code_review_bot/report/base.py
- bot/code_review_bot/report/phabricator.py
- bot/tests/test_reporter_phabricator.py
> Publish all issues as Phabricator LintResult

- bot/code_review_bot/tasks/clang_format.py
- bot/tests/fixtures/clang_format_groups.json
- bot/tests/test_clang.py
> Group neighboring clang format issues

- .isort.cfg
- backend/code_review_backend/app/settings.py
- backend/code_review_backend/app/urls.py
- backend/requirements.txt
> Add swagger generation & docs display on /docs

- backend/README.md
- backend/code_review_backend/issues/api.py
- frontend/src/Stats.vue
- frontend/src/store.js
> Faster stats with date limitations

- events/docker/Dockerfile
- tools/docker/bootstrap-mercurial.sh
Fixes #573 & clone of https://github.com/mozilla/bugbug/issues/1421
I'm pushing the PR to testing to test the memory reduction
> events: Use jemalloc to reduce RAM usage on Heroku

- .taskcluster.yml
> Don't run CI on PR closure

- events/code_review_events/bugbug_utils.py
- events/code_review_events/workflow.py
- events/tests/fixtures/taskcluster/task-bugbug-test-select.json
- events/tests/test_bugbug_utils.py
Following https://github.com/mozilla/community-tc-config/commit/8632602b8b3eaa12ef896eb23e84d0f398b80012
> Rename bugbug hooks and routes

- bot/code_review_bot/report/base.py
- bot/tests/test_reporter_phabricator.py
https://bugzilla.mozilla.org/show_bug.cgi?id=1679406
Will update the test once its reviewed
> Add the diff id in doc render code review comment on phabricator

- backend/requirements.txt
Reverts mozilla/code-review#838
> Revert "backend: Add an explicit dep for google-auth"

- bot/code_review_bot/workflow.py
- bot/tests/test_remote.py
> bot: Report build failure only if there are issues with Error level

- tools/docker/bootstrap-mercurial.sh
> tools: update hg to 5.9.1 and its related tools.

- bot/code_review_bot/report/phabricator.py
- bot/tests/test_reporter_phabricator.py
Quite a few bugs have been filed without changing the title. Let's try with a clearer placeholder.
> bot: Clarify the placeholder title in Bugzilla

- bot/code_review_bot/report/phabricator.py
- bot/tests/test_reporter_phabricator.py
> Add a link to diff section in Phabricator

- bot/code_review_bot/workflow.py
See https://bugzilla.mozilla.org/show_bug.cgi?id=1732902
> Bug 1732902 - Also publish in patch warnings in the bot backend

- bot/code_review_bot/report/phabricator.py
- bot/tests/conftest.py
- bot/tests/mocks/phabricator_diff_search_PHID-DREV-zzzzz-updated.json
- bot/tests/mocks/phabricator_diff_search_PHID-DREV-zzzzz.json
- bot/tests/test_reporter_phabricator.py
See https://bugzilla.mozilla.org/show_bug.cgi?id=1644982
> Bug 1644982 - If a newer diff exists on the patch, skip Phabricator comment publication

- events/code_review_events/workflow.py
- events/tests/test_workflow.py
> Report warning on Phabricator when the base revision is missing

- events/requirements.txt
> Move from aioredis to redis-py. Fixes #1446 #1445

- bot/code_review_bot/tasks/docupload.py
- bot/tests/test_docupload_task.py
> Various fixes for the DocUploadTask

- events/code_review_events/workflow.py
Revert undesired logging from commit d08be08c248f3cfa742d42570b7609ceb3d0690f
> Remove events debug messages

- .pre-commit-config.yaml
- backend/code_review_backend/issues/api.py
- backend/code_review_backend/issues/management/commands/load_issues.py
- backend/code_review_backend/issues/migrations/0001_initial.py
- backend/code_review_backend/issues/migrations/0002_compare_issues.py
- backend/code_review_backend/issues/migrations/0003_diff_repository.py
- backend/code_review_backend/issues/migrations/0004_issue_in_patch.py
- backend/code_review_backend/issues/migrations/0005_rename_check_issue_analyzer_check.py
- backend/code_review_backend/issues/migrations/0006_issuelink_initial.py
- backend/code_review_backend/issues/tests/commands/test_cleanup_issues.py
- backend/code_review_backend/issues/tests/test_issue.py
- backend/code_review_backend/issues/tests/test_revision.py
- bot/code_review_bot/cli.py
- bot/code_review_bot/revisions.py
- bot/code_review_bot/tasks/base.py
- bot/code_review_bot/workflow.py
- bot/tools/fix_missing.py
- events/code_review_events/workflow.py
- events/tests/conftest.py
- integration/tests/test_workflow.py
- tools/code_review_tools/log.py
Fix the current linting errors in CI tasks (e.g. https://community-tc.services.mozilla.com/tasks/QxQ76791TbSi10kmiasupg/runs/0/logs/public/logs/live.log)
> Update pre commit dependencies

- bot/code_review_bot/__init__.py
- bot/code_review_bot/backend.py
- bot/code_review_bot/revisions.py
- bot/tests/test_backend.py
- bot/tests/test_hash.py
> Handle erroneous issue file paths

- backend/code_review_backend/issues/api.py
- backend/code_review_backend/issues/tests/test_issue.py
> API endpoint listing issues for a path

- .taskcluster.yml
- events/build.sh
- events/code_review_events/version.json
- events/code_review_events/workflow.py
- events/docker/Dockerfile
- events/requirements-dev.txt
- events/tests/test_dockerflow.py
Depends on https://github.com/mozilla/libmozevent/pull/98 being merged + a new release for `libmozevent`
Closes #1557
> Support Dockerflow in events

- backend/code_review_backend/issues/management/commands/load_issues.py
Requires https://github.com/mozilla/code-review/pull/1462 (merged)
> Fix load issues management command

- bot/code_review_bot/tasks/clang_format.py
- bot/tests/test_clang.py
> Support empty diff file in ClangFormat parser

- bot/code_review_bot/report/phabricator.py
> Lower log level to info when no unresolved issues are left

- bot/code_review_bot/backend.py
> Avoid crashing when backend rejects issues payload

- bot/code_review_bot/cli.py
> Avoid lando extra publication in case revision is incomplete

- bot/code_review_bot/revisions.py
- bot/tests/test_hash.py
> Silently skip issues with invalid paths

- backend/requirements.txt
From #2304.
The API/application works fine. No breaking changes affect the app.
> Bump django to 5.1.0

- backend/Dockerfile
- backend/README.md
- backend/code_review_backend/app/settings.py
- backend/requirements.txt
- docker-compose.yml
> Setup django-environ in backend

- events/tests/conftest.py
based on / fixes the pipeline for #2394
> Update PhabricatorMock after libmozdata 0.2.8 (required user agent)

- bot/requirements.txt
- bot/tests/conftest.py
- events/requirements.txt
- events/tests/conftest.py
based on https://github.com/mozilla/code-review/pull/2399
based on / fixes the pipeline for #2395
> Update MockPhabricator after libmozdata 0.2.8 (required user agent)

- bot/requirements.txt
Reverts mozilla/code-review#2395
> Revert "build(deps): bump libmozdata from 0.2.7 to 0.2.8 in /bot"

- backend/code_review_backend/app/settings.py
- backend/code_review_backend/issues/management/commands/load_in_patch.py
> Add backend user agent to requests in load_in_patch management command

- .github/dependabot.yml
Feel free to reject if the labels are needed for the pull requests.
> simplify dependabot.yml

- .github/dependabot.yml
Reverts mozilla/code-review#2413
Fixes #2442
> Revert "simplify dependabot.yml"

- backend/code_review_backend/issues/api.py
- backend/code_review_backend/issues/tests/test_api.py
- backend/code_review_backend/issues/tests/test_compare.py
- bot/code_review_bot/backend.py
- bot/code_review_bot/config.py
- bot/code_review_bot/revisions.py
- bot/code_review_bot/workflow.py
- bot/tests/conftest.py
- bot/tests/test_backend.py
> Only use the bulk endpoint for issues creation

- backend/code_review_backend/issues/api.py
- backend/code_review_backend/issues/tests/test_api.py
- backend/code_review_backend/issues/tests/test_stats.py
> Fix tests failing locally with PostgreSQL

- bot/code_review_bot/cli.py
> Don't report 'fail' build status to Phabricator if publication is disabled

- bot/code_review_bot/report/phabricator.py
> Don't compare issues when there is no previous diff

- backend/code_review_backend/issues/tests/test_api.py
closes #2474 
But I only added the tests; I do not have access to Sentry so I can't see what caused the 500 errors or when, but duplicated issues do seem to be handled by the current code with 
```
issues = Issue.objects.bulk_create(
[Issue(**values) for values in validated_data["issues"]],
ignore_conflicts=True,
)
```
but maybe I'm missing something.
> Add duplicated issues tests for bulk entities creation endpoint

- backend/code_review_backend/issues/serializers.py
- backend/code_review_backend/issues/tests/test_api.py
> Allow issues bulk creation with existing hashes

- backend/code_review_backend/issues/serializers.py
- backend/code_review_backend/issues/tests/test_api.py
Closes #2519
We can rely on the number of returned issues. The API only show issues, but in the backend we should be able to manage many references to a same issue via multiple IssueLink entries.
I updated the endpoint so the output preserve issues order and added a test case with many links for a similar issue.
> Support multiple references to a single issue in the bulk creation

- bot/code_review_bot/revisions.py
I published a [new test revision](https://phabricator-dev.allizom.org/D3704) on phabricator-dev, and the task triggered by Phabricator did not get any information about a diff in the transactions.
The [resulting task ](https://firefox-ci-tc.services.mozilla.com/tasks/Qckop4W6Sju4tM1UdQXlNQ) failed early with the message:
```
Failed to load revision        error='No DIFF found in transactions' phabricator=https://phabricator-dev.allizom.org/api/ task=None
```
This PR adds a new behaviour, to fallback on the most recent diff available on the revision.
> Use most recent diff when not found in transaction

- bot/code_review_bot/revisions.py
This PR retries up to 5 times the first Phabricator API call for a Habormaster build.
As Phabricator revisions may take some time to become public (through internal automation), we need to retry that call.
This is similar to the [code ported from events](https://github.com/mozilla/code-review/blob/master/bot/code_review_bot/workflow.py#L283) that retries later in the workflow: we could probably remove that loop later on.
> Retry several times the first Phabricator API call

- bot/code_review_bot/analysis.py
- bot/code_review_bot/mercurial.py
- bot/code_review_bot/workflow.py
- bot/requirements.txt
- bot/tests/conftest.py
- bot/tests/mocks/phabricator_revision-search-PHID-DREV-666.json
- bot/tests/mocks/phabricator_revision-search-PHID-DREV-badutf8.json
- bot/tests/mocks/phabricator_revision-search-PHID-DREV-deadbeef.json
- bot/tests/mocks/phabricator_revision-search-PHID-DREV-solo.json
- bot/tests/mocks/phabricator_revision-search-PHID-DREV-zzzzz.json
- bot/tests/test_mercurial.py
Fixes #2827
Depends #2842 & https://github.com/mozilla/libmozdata/pull/258
> Skip already merged patches when building push to try

- bot/code_review_bot/report/lando.py
> Use a less scary message when no error is found before landing

- bot/code_review_bot/mercurial.py
- bot/tests/mocks/phabricator_search-PHID-DIFF-badutf8.json
- bot/tests/mocks/phabricator_search-PHID-DREV-deadbeefParent.json
- bot/tests/test_analysis.py
- bot/tests/test_mercurial.py
> Support checking out base revision on Git based repositories

- bot/code_review_bot/__init__.py
- bot/code_review_bot/tasks/coverage.py
- bot/tests/test_reporter_phabricator.py
> Skip the publication of coverage issue for files removed in the patch
