bot/code_review_bot/tools/taskcluster.py
bot/tests/test_tools.py

Needed on the latest version of TC client as `taskcluster._client_importer` is not available anymore.

bot: Update taskcluster service check

---

bot/code_review_bot/workflow.py
bot/taskcluster-hook.json
bot/tests/test_workflow.py

Refs #34 
I simply add the new `project.relman` routes in paralllel of the existing ones.
We'll run this for at least a week in production, in order to have both indexations at the same time.
The frontend will then be switched to the new route, and the old route will be removed from the bot.

bot: Add new Taskcluster routes

---

bot/code_review_bot/report/phabricator.py
bot/code_review_bot/tasks/coverity.py
bot/tests/test_remote.py
bot/tests/test_reporter_phabricator.py

This is a followup for #69 where we separate the build errors vs linting issues.

bot: separate errors agains the linting issues

---

bot/code_review_bot/workflow.py
bot/tests/test_workflow.py

Needed to avoid crashes due to node debugger linter in development (already landed the code-review attribute in tree) https://bugzilla.mozilla.org/show_bug.cgi?id=1575295#c3

Support all source-test without crashing, refs #27

---

.gitignore

For the developers that use `vscode` it would be nice to have the auto-generated workspace configuration excluded from `git`.

Add .vscode/ exclusion to .gitignore for vscode developers.

---

bot/code_review_bot/retrigger.py
bot/code_review_bot/workflow.py
bot/taskcluster-hook.json
bot/tests/test_workflow.py

Fixes #34
This is now possible as the production has run for 18 days with both namespaces : https://tools.taskcluster.net/index/project.relman.production.code-review.phabricator

Remove old releng routes

---

bot/code_review_bot/config.py

As the  `third_party` declaration has been removed from https://hg.mozilla.org/mozilla-central/file/tip/tools/clang-tidy/config.yaml by @sylvestre & @abpostelnicu in https://phabricator.services.mozilla.com/D44163
This break the bot :sob:

bot: Specify default path to third party

---

.isort.cfg
tools/code_review_tools/log.py

To be more consistent with code-coverage, and use our own naming scheme instead of release-services.

tools: Use our naming scheme for Sentry.

---

bot/code_review_bot/report/__init__.py
bot/code_review_bot/report/mail_builderrors.py
bot/code_review_bot/revisions.py
bot/tests/conftest.py
bot/tests/mocks/phabricator_diff_search.json
bot/tests/test_reporter_mail.py

Since `Phabricator` doesn't offer support for sending email when UnitTest failures happen we need to have this specific implementation in order to inform patch owners when build failure happen.

bot: Send email to differential owner when build failures are encountered, fixes #99

---

bot/code_review_bot/tasks/base.py
bot/requirements-dev.txt
bot/tests/test_coverity.py
bot/tests/test_issues.py

Refs #45.
Sending a warning when an absolute path is cleaned will allow us to track the usage function through Sentry.
As all analyzers on MC & NSS now output relative paths, we should be able to remove this cleanup if we see 0 warnings in the next few weeks.

bot: Add a warning when an absolute path is cleaned

---

bot/code_review_bot/report/mail_builderrors.py

As @La0 suggested we should add a log with the email that is used when sending a notification email when a build error occurs.

bot: Log email address that is used when reporting build errors.

---

bot/code_review_bot/__init__.py
bot/code_review_bot/report/mail_builderrors.py
bot/code_review_bot/tasks/coverity.py
bot/tests/conftest.py
bot/tests/test_remote.py
bot/tests/test_reporter_mail.py

For build errors when we send targeted emails we must used separate markdowns.

bot: add dedicated markdown for issues that are build errors.

---

bot/code_review_bot/revisions.py
bot/code_review_bot/workflow.py
bot/tests/test_reporter_debug.py
bot/tests/test_workflow.py

Export mercurial repo & revision in debug report

---

events/docker/Dockerfile

It is required to install hiredis without needing to compile the binary part (python 3.8 needs gcc for now...)

Use python 3.7 as base image

---

bot/code_review_bot/report/backend.py
bot/code_review_bot/revisions.py
bot/tests/test_reporter_backend.py
bot/tests/test_reporter_debug.py

A fix for [this bug](https://tools.taskcluster.net/groups/Q7RwlvU8S22bnspPyo_0Wg/tasks/Q7RwlvU8S22bnspPyo_0Wg/runs/0/logs/public%2Flogs%2Flive.log) happening when a Phabricator revision does not have the bugzilla id
I'll push it on production once landed

bot: Do not crash when bugzilla id is missing

---

backend/code_review_backend/issues/api.py
backend/code_review_backend/issues/serializers.py
backend/code_review_backend/issues/tests/test_api.py
backend/code_review_backend/issues/tests/test_diff.py
bot/code_review_bot/report/backend.py
bot/tests/conftest.py
bot/tests/test_reporter_backend.py

This is the first step to migrate the frontend to use the new backend (see #187)
- List of detailed diff (with revision) in read only on `/v1/diff/`
- CRUD Diff per revision api on `/v1/revision/XXX/diffs`
- Fixes in the bot to support this api instead of the previous endpoint

Diff management & detailed APIs

---

frontend/src/store.js

Now that the bot outputs always the same payloads for Issues, the frontend does not need to clean them up !

frontend: Use directly issues analyzer & check

---

bot/code_review_bot/workflow.py

The backend requires the repository (can't be null error)

Publish revision on backend once repo is known

---

backend/code_review_backend/app/settings.py
backend/code_review_backend/app/urls.py
backend/requirements-dev.txt

Helps writing more efficient DB queries

Add django debug toolbar

---

.taskcluster.yml

We forgot to remove the hook deployment in #216, as it's setup manually in https://phabricator.services.mozilla.com/D52309

Remove hook deploy on release

---

tools/code_review_tools/taskcluster.py

The backend needs to fetch its secret from the Community instance...

tools: Support TASKCLUSTER_ROOT_URL

---

.isort.cfg
bot/README.md
bot/code_review_bot/cli.py
tools/code_review_tools/taskcluster.py
tools/requirements.txt

The backend does not need it, as it can already run without a Taskcluster client.
The events use libmozevent TaskclusterConfig...
Refs #234

Support local configuration in the bot

---

bot/tools/copy_diff.py

I made that to copy any diff from the production instance on the dev instance, so i'm able to test comments & issues reporting without spamming anyone
```
$ python copy_diff.py 52765
Connected on source: https://phabricator.services.mozilla.com/api/
Connected on destination: https://phabricator-dev.allizom.org/api/
Loading revision 52765
Source revision is on repository mozilla-central
Found matching repository on destination as PHID-REPO-myz5mwsn6hrgkxn2ndos
Loading diffs for PHID-DIFF-alrlnuu3mn4ttmiver6v
Loading raw source diff 191621
Created new diff 2471 - PHID-DIFF-5xhvkrqy54ebrphqnmz5
Set diff properties
New revision created as https://phabricator-dev.allizom.org/D1535
```
[And it worked](https://phabricator-dev.allizom.org/D1535) :tada:

Add an admin tool to clone a revision between Phabricator instances

---

bot/code_review_bot/revisions.py
bot/tests/test_revisions.py

Phabricator does not always have that information (missing properties)

Support missing bugzilla id in phabricator data

---

.taskcluster.yml

Yesterday i had to ship manually the current production docker image on Heroku workers, as they do not use automatically the same image than the web workers.
This patch automatically updates both worker types, even if we do not always use them.

Use events docker image on Heroku workers too

---

tools/requirements.txt

A new `python:3.7-alpine` was released that [breaks building a dependency](https://community-tc.services.mozilla.com/tasks/Esj8VQ3ETCKA_aH84L5jnw/runs/0/logs/https%3A%2F%2Fcommunity-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FEsj8VQ3ETCKA_aH84L5jnw%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log)

tools: Update deps limits

---

events/code_review_events/workflow.py

Since we don't consume messages when publication is disabled: https://github.com/mozilla/code-review/blob/02d31adcbb878d50fb7f8846ae6d29150178bea0/events/code_review_events/workflow.py#L356-L362.

events: Don't register for pulse notifications when publication is disabled

---

bot/code_review_bot/cli.py
bot/code_review_bot/report/phabricator.py
bot/code_review_bot/revisions.py
bot/code_review_bot/workflow.py
bot/tests/conftest.py
bot/tests/test_reporter_phabricator.py

- Removes dependency on `PhabricatorAPI` in the constructor
- Explicitly create a revision from a try task + phabricator api
Preparation work for #211 to be able to create `Revision` from an autoland decision task payload

Cleanup revision creation

---

events/code_review_events/workflow.py

Needed to run the current code on Heroku testing.
Otherwise we send invalid parameters on Pulse, leading to an `AmqpClosedConnection`

Fix libmozevent 1.0.9 pulse usage

---

events/code_review_events/workflow.py

Use bus.run to process builds from the webserver

---

backend/code_review_backend/issues/serializers.py
backend/code_review_backend/issues/tests/test_api.py
backend/code_review_backend/issues/tests/test_diff.py
bot/code_review_bot/backend.py
bot/code_review_bot/config.py
bot/code_review_bot/revisions.py
bot/tests/conftest.py
bot/tests/test_backend.py
bot/tests/test_reporter_debug.py

So we don't have to maintain lists of slugs, and can use any repository (even Github).

Use repository urls instead of assuming slugs

---

bot/code_review_bot/__init__.py
bot/code_review_bot/backend.py
bot/tests/test_backend.py

[Sample failure](https://firefox-ci-tc.services.mozilla.com/tasks/KAHwfCmqT1asHJij4uCPsA/runs/0/logs/https%3A%2F%2Ffirefox-ci-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FKAHwfCmqT1asHJij4uCPsA%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log)

Fix clang tidy bad ../../x paths

---

events/code_review_events/bugbug_utils.py
events/code_review_events/workflow.py
events/tests/fixtures/taskcluster/task-bugbug-test-select.json
events/tests/test_bugbug_utils.py

Fixes #327
Requires a new version of libmozevent, which I will release tomorrow.

Use EphemeralStorage class from libmozevent to store builds and pushes related to test selection

---

bot/code_review_bot/report/base.py
bot/code_review_bot/report/mail.py
bot/tests/conftest.py
bot/tests/test_reporter_mail.py
bot/tests/test_reporter_phabricator.py

Use task names directly in all report comments

---

events/code_review_events/workflow.py

Otherwise we get an exception:
```
2019-12-09T10:52:38.406540+00:00 app[worker.1]: 2019-12-09 10:52:38.382754 [ERROR   ] libmozevent.utils: Failure while running async tasks (error='An asyncio.Future, a coroutine or an awaitable is required')
2019-12-09T10:52:38.963512+00:00 app[worker.1]: Traceback (most recent call last):
2019-12-09T10:52:38.963531+00:00 app[worker.1]:   File "/usr/local/lib/python3.7/site-packages/libmozevent-1.1.0-py3.7.egg/libmozevent/utils.py", line 49, in _run
2019-12-09T10:52:38.963533+00:00 app[worker.1]:     task = asyncio.gather(*awaitables)
2019-12-09T10:52:38.963540+00:00 app[worker.1]:   File "/usr/local/lib/python3.7/asyncio/tasks.py", line 746, in gather
2019-12-09T10:52:38.963542+00:00 app[worker.1]:     fut = ensure_future(arg, loop=loop) …
```

events: Fix bugbug utils setup call

---

events/code_review_events/workflow.py

Since I was here, I've also removed a `return True` which is no longer needed in newer releases of libmozevent.

events: publish_results should be async in order to use parallel bus processing

---

events/code_review_events/bugbug_utils.py
events/code_review_events/workflow.py
events/tests/fixtures/phabricator/user-search-ehsan-heycam.json
events/tests/fixtures/phabricator/user-search-ehsan.json
events/tests/test_bugbug_utils.py

This way we can avoid loading reviewers from Phabricator for each diff.

Load enabled reviewers just once at startup

---

backend/code_review_backend/issues/models.py
backend/code_review_backend/issues/tests/test_revision.py

backend: Always serve a valid Phabricator revision url

---

backend/code_review_backend/issues/management/commands/load_in_patch.py

Found 2 bugs when running on Heroku testing:
1. weirdly i get a decode exception using parsepatch there
2. saw a lot of diffs processed multiple times, my sql request lacked a `DISTINCT`

Fix bugs in load_in_patch script on Heroku

---

backend/code_review_backend/issues/management/commands/load_in_patch.py

Followup of #398 
Reported upstream on https://github.com/mozilla/parsepatch/issues/11

Workaround to get parsepatch to run on alpine

---

backend/code_review_backend/app/settings.py
backend/code_review_backend/issues/management/commands/load_in_patch.py

Another issue found on testing, the postgresql connection does not work in a multiprocessing context (whereas with sqlite in dev it works).
So i need to close all pre-existing connections before starting the processes, so that each process gets its own connection.

Dedicated Postgresql connection on each process

---

tools/docker/bootstrap-mercurial.sh

Reverts mozilla/code-review#402
We need to wait until robustcheckout is fixed.

Revert "tools: Use Mercurial with Python 3"

---

bot/code_review_bot/report/phabricator.py
bot/tests/test_reporter_phabricator.py

Prep work for #364 
I'm removing the unused Harbormaster publication mode in order to have only one publication workflow on Phabricator:
- one comment to summarize issues
- inline comments for in patch issues
- unit results for build errors
- lint results for extra errors (outside of patch) :new:

Remove useless Harbormaster publication mode

---

bot/code_review_bot/__init__.py
bot/code_review_bot/tasks/clang_format.py
bot/code_review_bot/tasks/clang_tidy.py
bot/code_review_bot/tasks/coverage.py
bot/code_review_bot/tasks/coverity.py
bot/code_review_bot/tasks/default.py
bot/code_review_bot/tasks/infer.py
bot/code_review_bot/tasks/lint.py
bot/tests/test_clang.py
bot/tests/test_coverage.py
bot/tests/test_coverity.py
bot/tests/test_lint.py

Prep work for #364 
Every issue needed to implement `as_phabricator_lint` & `as_phabricator_unitresult`. But we have re-organized the Issue inner data earlier, allowing us to have a unique implementation for these methods.
The unit results are only used by Coverity (for build errors), but every Issue will be able to post a lint result now (for an error outside the patch).
The good news is that the payload do not change a lot (even if they were not used until now) as you can see in the unit tests.

Common Phabricator unit & lint results

---

backend/code_review_backend/issues/api.py
backend/code_review_backend/issues/models.py
backend/code_review_backend/issues/tests/test_issue.py
bot/code_review_bot/__init__.py
bot/code_review_bot/report/phabricator.py
bot/tests/test_default.py
bot/tests/test_hash.py
bot/tests/test_lint.py
bot/tests/test_remote.py
bot/tests/test_reporter_phabricator.py

Requires #417 
Refs #364 
This PR will report all errors, even if they are outside a patch (as Phabricator lint results).
:information_source: I'm adding some unit tests to cover that new publication.

Publish errors

---

bot/code_review_bot/report/phabricator.py
bot/tests/test_reporter_phabricator.py

Fixes #25 
This PR support both modes of operations:
- Maintains the current mode where errors & warnings in patch are published as inline (when `publish_errors: False` in config & by default)
- Publishes all errors (regardless of their in_patch state) as lint results  (when `publish_errors: Trie` in config)

Add switch to publish errors & always publish errors as Lint results when enabled

---

frontend/src/Stats.vue

Sort issue stats by detected or publishable

---

events/code_review_events/workflow.py

I don't know if it's actually useful, but I guess it can't hurt.

events: Await any pending tasks at shutdown

---

events/code_review_events/bugbug_utils.py
events/tests/fixtures/taskcluster/task-bugbug-test-select.json
events/tests/test_bugbug_utils.py

Depends on https://github.com/mozilla/bugbug/pull/1243.

events: Support passing the Phabricator deployment to bugbug

---

.flake8
bot/code_review_bot/report/phabricator.py
bot/tests/test_reporter_phabricator.py
events/code_review_events/bugbug_utils.py
events/tests/test_bugbug_utils.py

This way bugbug can skip jobs which are not runnable.
Note: this will make test selection start a little later, as we start it after pushing to try rather than when we get the notification from Phabricator, but this should be a limited delay.

events: Pass runnable-jobs from the decision task when triggering a bugbug test selection task

---

.taskcluster.yml

As skopeo cannot upload the old image format produced by Taskcluster dind, to update testing or production, we need to stick to privileged workers using img.
I'm still building the bot docker image with dind (that's the only one needed with dind on firefox-ci).
Also [Bug 1594102](https://bugzilla.mozilla.org/show_bug.cgi?id=1594102) is a bit stuck, so the workflow may change later on

Use dind build only for bot

---

bot/code_review_bot/report/base.py
bot/code_review_bot/workflow.py
bot/tests/conftest.py
bot/tests/test_reporter_phabricator.py
bot/tests/test_workflow.py
events/code_review_events/bugbug_utils.py
events/requirements.txt
tools/code_review_tools/treeherder.py
tools/requirements.txt

Hopefully almost fixes #41 ...
Several things are happening here:
1. i'm sharing the treeherder job url between events & bot - it's setup in code_review_tools
2. events is updated to use that method
3. the bot uses the treeherder url for a task failure (instead of the Taskcluster frontend view) - displaying potential issues
4. A `DefaultTask` is used for all `source-test-*` tasks, meaning that any failing task from `source-test` will use the task failure mechanism.
A followup would be to report such failures through use unit results instead of a comment.

Use treeherder url for task failures

---

bot/code_review_bot/revisions.py
bot/code_review_bot/workflow.py
bot/tests/conftest.py
bot/tests/test_remote.py
bot/tests/test_reporter_debug.py

Fixes #480
In the end, i used the heuristic `decision task id == try group id`, as it's possible to create tasks from the decision tasks without adding the decision task as a dependency, thus making it impossible to trace it back

Use task group id to find decision task

---

bot/code_review_bot/cli.py
bot/code_review_bot/config.py
bot/code_review_bot/revisions.py
bot/tests/conftest.py
bot/tests/mocks/phabricator_repository_search.json
bot/tests/test_patch.py
bot/tests/test_remote.py
bot/tests/test_workflow.py

Fixes #479
When releasing, i'll simply need to move the existing `repositories` configuration in secret in **common**  section, and then add the relevant decision keys.

Use repositories config from secret to find mercurial infos in decision task

---

bot/code_review_bot/config.py
bot/code_review_bot/report/base.py
bot/code_review_bot/revisions.py
bot/tests/conftest.py
bot/tests/test_reporter_phabricator.py

bot: The repo parameter of the Treeherder URL should be the name of the repository, not its URL

---

bot/requirements-dev.txt

The latest virtualenv release breaks black setup in pre-commit.

Fix black setup on CI

---

.taskcluster.yml

The docker image expired yesterday on the firefox-ci Taskcluster instance, so the bot did not publish any results for a day.
I've triggered a new production build, available for 2 weeks: https://firefox-ci-tc.services.mozilla.com/tasks/groups/MQugUdeIQjqasPWJq_M-AA

Extend docker image lifetime to 6 months

---

bot/tests/conftest.py
bot/tests/test_reporter_phabricator.py

Fixes #421 
Pave the way to use lint/unit results instead of comments.

Use common mockup class for Phabricator API

---

bot/code_review_bot/__init__.py
bot/code_review_bot/report/base.py
bot/code_review_bot/report/phabricator.py
bot/code_review_bot/revisions.py
bot/code_review_bot/tasks/base.py
bot/code_review_bot/tasks/clang_format.py
bot/code_review_bot/tasks/clang_tidy.py
bot/code_review_bot/tasks/coverage.py
bot/code_review_bot/tasks/coverity.py
bot/code_review_bot/tasks/default.py
bot/code_review_bot/tasks/infer.py
bot/code_review_bot/tasks/lint.py
bot/code_review_bot/workflow.py
bot/tests/conftest.py
bot/tests/test_clang.py
bot/tests/test_coverage.py
bot/tests/test_coverity.py
bot/tests/test_hash.py
bot/tests/test_infer.py
bot/tests/test_issues.py
bot/tests/test_lint.py
bot/tests/test_patch.py
bot/tests/test_remote.py
bot/tests/test_reporter_mail.py
bot/tests/test_reporter_phabricator.py

Fixes #554
This PR allow us to customize the analyzer name displayed in Phabricator (and other parts of the system).
The `AnalysisTask` instances are now fully accessible from their issues (instead of a single string), which allows us to have some logic from the tasks accessible when building payloads for Phabricator.
Two new methods are available on the `AnalysisTask` sub classes:
- `build_help_message` customizes the optional help message in the summary comment
- `display_name` is a nicer name, only used for humans (:robot: still use the shorter and unique `name`).

Use nicer analyzer names on Phabricator

---

bot/code_review_bot/report/base.py
bot/tests/test_reporter_mail.py
bot/tests/test_reporter_phabricator.py

This will display detailed stats in the summary comments:
- 1 build error found by XX
- 1 build error and 2 defects found by YY
- 3 defects found by ZZ

Display build error & defects stats in summary comment

---

bot/code_review_bot/__init__.py
bot/code_review_bot/tasks/coverity.py
bot/tests/test_remote.py
bot/tests/test_reporter_phabricator.py

It will display `Build Error` as lint name, when a Coverity issue is a build error (defaulting to `Coverity` otherwise).
I also added the stack to the build error reporting, now that we use a lint result, it can be shown without breaking the display

Display build error as coverity name

---

bot/code_review_bot/report/debug.py

This bug crashes the final execution of the bot when a clang-format is present (the debug reporter crashes, and i'm lucky this is the ultimate step in the bot, nothing is really affected.)

Fix bug preventing report serialization

---

.isort.cfg
bot/tests/conftest.py
bot/tests/test_reporter_phabricator.py
events/tests/test_bugbug_utils.py
tools/code_review_tools/treeherder.py

This way we can avoid a API call to Treeherder.
This capability was recently added to Treeherder in https://bugzilla.mozilla.org/show_bug.cgi?id=1605426.
Fixes #371

Use selectedTaskRun instead of selectedJob for the Treeherder link pointing to a given task

---

bot/code_review_bot/tasks/clang_tidy.py
bot/code_review_bot/tasks/coverity.py
bot/tests/conftest.py
bot/tests/test_clang.py
bot/tests/test_remote.py
bot/tests/test_reporter_mail.py
bot/tests/test_reporter_phabricator.py

`Coverity` proved to be suboptimal when we want to detect build errors so we must stop using it and switch to `clang-tooling`, in this case `clang-tidy`.

bot: For C++ build error reporting stop using `Coverity` that proved to be suboptimal and use `clang-tidy` for this.

---

docs/publication.md
events/code_review_events/workflow.py
events/tests/fixtures/taskcluster/task-gecko-decision.json

Treeherder is a code name for a Mozilla project
CI is the actual wording for this

Rename the link to Treeherder from 'Treeherder Jobs' to 'CI (Treeherder) Jobs'

---

bot/code_review_bot/report/base.py
bot/tests/test_reporter_phabricator.py

Please see [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1640468).

bot: Remove extra space in message before question mark.

---

bot/code_review_bot/tasks/clang_tidy.py
bot/tests/test_reporter_phabricator.py

Sometimes the issue detected by `clang-tidy` are in header files and thus the message that is displayed in `phabricator` includes those headers paths, this is something not useful sine they are not compilation units the message is actionable.

bot: Add `--outgoing` for `clang-tidy` running message.

---

bot/code_review_bot/report/base.py
bot/code_review_bot/tasks/clang_tidy_external.py
bot/code_review_bot/workflow.py
bot/tests/test_remote.py
bot/tests/test_reporter_phabricator.py
bot/tests/test_workflow.py

This adds support for new static analysis, called "source-test-clang-tidy-external", which we are enabling in [Bug 1666808](https://bugzilla.mozilla.org/show_bug.cgi?id=1666808) (see also changeset in [phab](https://phabricator.services.mozilla.com/D91149)).
It works locally and pytest & flake8 pass, but I'm sure there's going to be some iteration.
The reported message looks like this, happy to modify to make it work for you folks.

Add support for source-test-clang-tidy-external

---

bot/code_review_bot/tasks/clang_tidy_external.py
bot/code_review_bot/workflow.py
bot/tests/test_remote.py
bot/tests/test_reporter_phabricator.py
bot/tests/test_workflow.py

This patch adds testing for the case in which clang-tidy-external does not report clang-diagnostic errors,
which ought to be caught by the other clang-tidy jobs or during built.
We also improve reporting logic to ensure that only `mozilla-civet`-prefixed
diagnotics are reported.

Improve test coverage for clang-tidy-external

---

bot/code_review_bot/tasks/clang_tidy_external.py

Prevent a false-positive that this reporter generates.
This is a temporary fix, untill the underlying issue is fixed.

bot: for clang_tidy_external do not report build-errors.

---

backend/code_review_backend/issues/api.py

Because of performance issues that is caused by a great number of entries in the `issues.issue` table we should not look at historic data that is not that relevant.

backend: For the postgresql `DiffViewSet` do not use historic diffs older than 3 months.

---

bot/code_review_bot/cli.py
bot/code_review_bot/report/__init__.py
bot/code_review_bot/report/lando.py
bot/requirements.txt
bot/tests/conftest.py
bot/tests/test_reporter_lando.py
events/code_review_events/workflow.py
events/requirements.txt
events/tests/fixtures/phabricator/message-PHID-HMBT-icusvlfibcebizyd33op-fail-unit.json
events/tests/test_workflow.py

With https://github.com/mozilla-conduit/lando-api/pull/172 we have support in lando to send warnings.
We are going to send two warnings for each diff for each revision:
- Once the revision has been updated/created an initial message will be send indicating the user that there are linters running:"Review time linters are still running. Are you sure you want to continue?"
- Just as the review bot finishes posting issues in phab we send the 2nd message with the issues or if there aren't any we clear previous send message.

Add lando warnings support

---

bot/code_review_bot/cli.py

We are using `requests` in the `backend` module, so track the `requests.exceptions.HTTPError` and update `phabricator`.
This fixes #984.

bot: when a generic bot failure occurs also report it in phabricator.

---

bot/code_review_bot/backend.py

bot: do not throw exceptions when backend fails.

---

bot/code_review_bot/revisions.py
tools/requirements.txt

This must be merged in master after taskcluster is released, version greater than 44.2.2

bot: publish artitact as `bytes` instead of `string`.

---

bot/code_review_bot/revisions.py

bot: remove logger when issue path is not in revision.

---

events/code_review_events/workflow.py

Running the events loop causes this error:
```
[ERROR   ] libmozevent.utils: Failure while running async tasks (error="Error while reading from ec2-34-193-21-24.compute-1.amazonaws.com:30059 : (104, 'Connection reset by peer')")
Traceback (most recent call last):
File "/usr/local/bin/code-review-events", line 33, in <module>
sys.exit(load_entry_point('code-review-events==1.4.6', 'console_scripts', 'code-review-events')())
File "/usr/local/lib/python3.9/site-packages/code_review_events-1.4.6-py3.9.egg/code_review_events/cli.py", line 78, in main
events.run()
File "/usr/local/lib/python3.9/site-packages/code_review_events-1.4.6-py3.9.egg/code_review_events/workflow.py", line 564, in run
run_tasks(asyncio.Task.all_tasks())
AttributeError: type object '_asyncio.Task' has no attribute …
```

events: all_tasks is now part of asyncio

---

backend/code_review_backend/issues/api.py

Ref. #1044
Improves overall performance on the endpoint, especially on small data ranges (blue line is this PR, red line is master) :
A Vacuum can probably be performed on the database too, I got acceptable times on my setup with a production dump (<10s).

Cast creation date as timestamptz to build issues checks stats

---

bot/code_review_bot/report/phabricator.py
bot/tests/mocks/phabricator_edge_search.json
bot/tests/test_reporter_phabricator.py

Follow-up of #561 and #690
Closes #553

Bug 1610715 - Add a hint when error comes from a parent revision

---

.isort.cfg
backend/requirements.txt
tools/code_review_tools/log.py
tools/requirements.txt

Closes #1225 
Please test carefully this PR, I am not really familiar with **Sentry** and **Papertrail** and may have missed some details that may no longer appear in the logs or in Sentry issues and are very crucial for you. As you will see in the following screenshots, I was able to test the **Sentry** integration using a real instance. Regarding **Papertrail**, I simply redirected the output to `/dev/log`, rather than to a real Papertrail instance using a `host` and a `port`, so that I could check the format of the logs but that's all.
As stated in issue #1225, the concern encountered is that the Sentry issue name almost always includes a unique context which prevents issues from being grouped together by having several different events attached.
**Currently we have:**
Issue number 1 …

Use sentry_sdk instead of raven and improve Sentry grouping

---

events/requirements.txt

Refs. #135
This should fix errors when pushing builds to try

Update libmozevent dependency to 1.1.14

---

tools/code_review_tools/log.py

Fix a bug that appeared after merging #1253, that raises an error `Attempt to overwrite '*' in LogRecord` (with `*`, a common attribute from `LogRecord`) when several logs were processed by `structlog` processors.
In `logging` documentation:
> The keys in the dictionary passed in _extra_ should not clash with the keys used by the logging system. (See the section on [LogRecord attributes](https://docs.python.org/3/library/logging.html#logrecord-attributes) for more information on which keys are used by the logging system.)
The line raising the error in `logging`:
https://hg.python.org/cpython/file/3.5/Lib/logging/__init__.py#l1394
The quick fix implemented in this PR is to rename all clashing attributes by adding a `_` character.

Fix "Attempt to overwrite '*' in LogRecord"

---

.pre-commit-config.yaml

Since flake8 move away from gitlab to github we should do the same otherwise our infra will be remain buster. Same thing we did for mozilla/libmozevent

Move flake8 from gitlab to github.

---

bot/code_review_bot/tasks/base.py
bot/tests/conftest.py
bot/tests/test_remote.py

This is required to download a task's artifact with a development setup, otherwise the request will fail with a HTTP_303 (e.g. https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/JN1CcLiYRJ2Ehx2TbJJdDA/runs/0/artifacts/public%2Fcode-review%2Fmozlint.json)

Allow HTTP_30x redirections retrieving artifacts

---

bot/code_review_bot/report/phabricator.py
bot/tests/test_reporter_phabricator.py

The text was simply appearing as a title because the delimiter (`---`) was directly placed under that block.
Reformatting the `COMMENT_DIFF_FOLLOWUP` variable (with an extra line break at the end) was enough, but I also updated the horizontal rule to prevent that behavior in the future (supplementary line breaks will not be rendered as markdown).

Bug 1803963 - Prevent the horizontal delimiter to act as header in Phabricator comments

---

bot/code_review_bot/report/phabricator.py

It included a f-string expression even if it wasn't an f-string

bot: Fix 'no new issues' warning message

---

bot/code_review_bot/workflow.py
bot/tests/test_remote.py
bot/tests/test_workflow.py

This type of tasks doesn't expose issues.json so we should ignore it.

In `build_tak` for tasks that do not match anything returrn None.

---

bot/code_review_bot/revisions.py

Make 'path' a parameter of the "Element is not valid" warning to allow better grouping

---

bot/code_review_bot/report/debug.py
bot/code_review_bot/report/lando.py
bot/code_review_bot/report/mail.py
bot/code_review_bot/report/mail_builderrors.py
bot/code_review_bot/report/phabricator.py
bot/code_review_bot/tasks/base.py
bot/code_review_bot/tasks/tgdiff.py
bot/code_review_bot/workflow.py
bot/requirements.txt
bot/tests/conftest.py
bot/tests/test_reporter_debug.py
bot/tests/test_reporter_lando.py
bot/tests/test_reporter_mail.py
bot/tests/test_reporter_phabricator.py
bot/tests/test_tgdiff_task.py

Depends on https://github.com/mozilla/libmozdata/pull/214 being merged + a new release for **libmozdata**
Closes #1475

Add #taskgraph-reviewers on the Phabricator revision following the output of the TGDiff task

---

.taskcluster.yml

The `img` tool seems to be no longer actively maintained. Fuzzing also switched to podman in https://github.com/MozillaSecurity/orion/pull/242.
Credit to @matt-boris for the idea, finding the `BUILD_TOOL` env var, and discovering the fuzzing PR!

Use podman rather img to build images

---

.taskcluster.yml

We (taskcluster team) intend to remove support for Ubuntu 22.04 in the near future.

Migrate from Ubuntu 22.04 to Ubuntu 24.04 in CI

---

tools/code_review_tools/log.py
tools/requirements.txt

Closes #2250
Closes #1416 
Closes #2234 
Closes #2209 
Closes #2249
In sentry 2.X the module `sentry_sdk.integrations.logging.COMMON_RECORD_ATTRS` is not available anymore.
Fortunately, we do not need it anymore, simply relying on internal features from recent `structlog`.
I tested these changes using this redacted snippet that enables both sentry & papertrail publication on test projects:
```python
from code_review_tools.log import init_logger
import structlog
init_logger(
"bot",
channel="dev",
PAPERTRAIL_HOST="xxx.papertrailapp.com",
PAPERTRAIL_PORT=yyy,
SENTRY_DSN="https://whatever.ingest.us.sentry.io/zzzz"
)
logger = structlog.get_logger("test.log")
logger.info("This is Info")
logger.warning("This is warning")
logger.error("This is error", my="arg", test="ok")
print(1/ 0)
```
Here are …

Use modern sentry SDK

---

backend/code_review_backend/issues/management/commands/cleanup_issues.py
backend/code_review_backend/issues/tests/commands/test_cleanup_issues.py

Refs #1539 
I simply remove the repository filters to process all revisions no matter where they come from.
The `logging.basicConfig` is removed, as it became useless since sentry+logging update.

Remove repository filters in cleanup_issues command

---

backend/code_review_backend/app/settings.py
docker-compose.yml
docs/docker.md

Refs #1539 
In order to reproduce locally the heroku stack I built this simple docker-compose stack with the Postgres DB & backend running.
This allows me to load an Heroku dump and use it from the backend either in docker or in dev mode

Docker compose stack

---

bot/tests/conftest.py
bot/tests/fixtures/sentry_event_after.json
bot/tests/fixtures/sentry_event_before.json
bot/tests/test_tools.py
tools/code_review_tools/log.py

Closes #2288 
This removes all ANSI color codes from any event being sent to Sentry. This supports breadcrumbs (context for sentry) and log messages.
The code is a bit defensive as the payload may vary across events
Here is a screenshot of my test Sentry project with both versions from master & this PR

Remove ANSI color codes from sentry events

---

.taskcluster.yml

In https://bugzilla.mozilla.org/show_bug.cgi?id=1907217 we're making scopes more explicit for branches. Because of this, pushes to branches not named in that repository will not be able to run. If this will be problematic, or we need to add more branches to this list, please let me know and we'll sort it out!

restrict on push builds to `master` and `production` in taskcluster

---

backend/code_review_backend/issues/management/commands/load_issues.py
backend/requirements.txt

* `load-in-patch`: Missing a requirement
* `load-issues`: Using deprecated attribute `phid` (instead of `phabricator_id`)

Fix management commands

---

backend/code_review_backend/app/settings.py

Required to use a development frontend with the dockerized stack.
This allows configuring the CORS origins through an environment variable, still supporting override by taskcluster in Heroku.
The `CORS_ORIGIN_WHITELIST` setting was renamed `CORS_ALLOWED_ORIGINS` (see [documentation](https://pypi.org/project/django-cors-headers/#configuration))

Configure CORS origins with django-env

---

bot/code_review_bot/backend.py
bot/tests/test_backend.py

Closes #1577
Ideally I will add a test case for this.

Silently skip issues from rustfmt linter with path "."

---

bot/code_review_bot/cli.py
bot/requirements.txt
events/code_review_events/cli.py
events/requirements.txt
tools/code_review_tools/libmozdata.py
tools/requirements.txt

This PR configures libmozdata using a local Configuration classs, that does not rely on files but instead build dynamically the user agent by looking up the provided package version.
There is no file to add in the Docker image, and the version in the user agent always increment.

Configure libmozdata from tools

---

bot/tests/fixtures/sentry_event_after.json
bot/tests/fixtures/sentry_event_before.json
tools/requirements.txt

Library aiohttp had dropped async-timeout asrequirement on Python 3.11+ systems in version 3.9.0.

remove dependency on async-timeout

---

.taskcluster.yml
backend/code_review_backend/issues/migrations/0014_unique_hash.py

I found out that the commited version of the 0014 migration is incomplete (mismatching max length).
It's not a big deal as it did not run on prod yet, but to avoid this in the future I also added a CI check that will prevent merging invalid migration states

Fix Issue.hash max length in migration

---

bot/code_review_bot/workflow.py

Closes #2508 
The bug is trivial to fix, but the [task](https://firefox-ci-tc.services.mozilla.com/tasks/BHDyOiRpTeCWly7D90XTNw) that triggered the exception is unsupported.
A log line now mentions it in the bot execution with this patch:
```
2024-11-13 09:38:44.000441 [WARNING ] [warning  ] Missing firefox-source-docs-url.txt
2024-11-13 09:38:44.000442 [WARNING ] [warning  ] An erroneous task processed some artifacts and found no issues or patches id=BHDyOiRpTeCWly7D90XTNw task=source-test-doc-upload
```
As mentionned, this is due to `public/firefox-source-docs-url.txt` artifact missing. We cannot do much more on the bot side

Do not crash on unsupported tasks

---

backend/code_review_backend/issues/serializers.py

This should fix backend unit tests and allow another push on testing (last one [did not complete](https://community-tc.services.mozilla.com/tasks/groups/D10BRBUGTt2OtsxVcO0V5w))

Preserve initial issues order during bulk create

---

backend/code_review_backend/issues/serializers.py
backend/code_review_backend/issues/tests/test_api.py

Closes #2516
The approach by chunk would make the code more complex and still slow. I think the main issue here was the number of IssueLink returned by the JOIN. On my DB 10 hashes may return thousands of links.
I added a filter by revision/diff for existing issues. The estimated cost in pgadmin dropped from max `49265.77` to max `91.8` on my database. I also added an iterator() to be sure we avoid a memory issue there.

Filter fetched existing issues by revision and diff

---

bot/code_review_bot/revisions.py
bot/tests/conftest.py
bot/tests/test_revisions.py

Closes https://mozilla.sentry.io/issues/6064254923
Refs #2260 
This prevents the bot from crashing when a revision has no diff set and the `repr` method is called on the revision.
This only happens in the [main error handling case](https://github.com/mozilla/code-review/blob/master/bot/code_review_bot/cli.py#L202-L204) for autoland revisions, but it prevents the bot from reporting error state on both phabricator & lando.
Here is an [example task](https://firefox-ci-tc.services.mozilla.com/tasks/S8p_nBz-RUe-GVrK05pCZg/runs/0/logs/public/logs/live.log) where this happen.

Support autoland on Revision.__repr__

---

backend/code_review_backend/issues/serializers.py
backend/code_review_backend/issues/tests/test_api.py

Refs #2260 
Closes https://mozilla.sentry.io/issues/6072452921 (a lot of 500s on both instances)
I noticed an important issue on the backend that prevent issues creation when an issue is already linked to a revision through a previous diff. This case happens often now that we have de-duplicated issues.
The bulk endpoint was iterated over recently, bringing too much complexity.
I was able to simplify it so it runs in 4 steps:
1. create all issues in a single `bulk_create` call, using unicity constraints to prevent duplications
2. retrieve all issues from DB to get existing IDs (as bulk_create otherwise provides its generated but non-commited IDs)
3. directly create all issue links in a single `bulk_create` call, using unicity constraints to prevent duplications
4. build list of dicts for …

Simplify bulk issues creation

---

events/requirements.txt

This reverts commit 0b66468383f1b34f7045e0ccbce5a4cd52a007ae.
The usage of [this patch](https://github.com/mozilla/libmozevent/commit/3ce10c6e164d25169acaef878eb36e103b147fce) seems invalid, as it raises https://mozilla.sentry.io/issues/6075721195

Revert libmozevent to 1.1.28

---

bot/code_review_bot/analysis.py
bot/code_review_bot/cli.py
bot/code_review_bot/config.py
bot/code_review_bot/revisions.py
bot/code_review_bot/workflow.py
bot/requirements.txt
bot/tests/conftest.py
bot/tests/mocks/phabricator_build_search.json
bot/tests/mocks/phabricator_buildable_search.json
bot/tests/mocks/phabricator_diff_search_PHID-DIFF-testABcd12.json
bot/tests/mocks/phabricator_edge_search.json
bot/tests/mocks/phabricator_project_search.json
bot/tests/mocks/phabricator_target_search.json
bot/tests/mocks/phabricator_transaction_search.json
bot/tests/test_analysis.py

Refs #2518 
This is the new code-review bot behaviour to support Phabricator webhook triggers, replacing the events system running on Heroku.
The revision & diffs are loaded using these environment variables:
-  `PHABRICATOR_OBJECT_PHID` which is the revision phid
- `PHABRICATOR_TRANSACTIONS` which is a json encoded list of Phabricator transactions, which contains the history of the revision at the time of the trigger
The bot must:
- retrieve the revision, repository, diff and Harbormaster target from Phabricator API
- clone the base repo at its tip
- load the stack of patches from Phabricator
- apply them on the clone
- push to try
- report state (or errors) on Phabricator
- report state (or errors) on Lando
The bot now depends on libmozevent, allowing the code port to be relatively …

Port events workflow to bot

---

bot/code_review_bot/analysis.py
bot/code_review_bot/workflow.py

This PR fixes the bug encoutered when trying to push Lando updates upon Phabricator triggers ([example](https://firefox-ci-tc.services.mozilla.com/tasks/VXUCtq-qRLaSEFYFHKoLqg/runs/0/logs/public/logs/live.log))
The `phabricator.update_state` method was not triggered, thus not updating the `build.revision` dict using data from Phabricator, which was expected by the Lando publication code.
I was able to test this by running
```
export PHABRICATOR_OBJECT_PHID=PHID-DREV-yqqy3neexfvt4eiyppqn
export PHABRICATOR_OBJECT_TYPE=DREV
export PHABRICATOR_TRANSACTIONS='["PHID-XACT-DREV-y7wk6gi2ifoz6sp","PHID-XACT-DREV-oamyuv56fp3ud43","PHID-XACT-DREV-c2ezdtdzoynkrtx","PHID-XACT-DREV-b7ka37gfj277shk","PHID-XACT-DREV-3yasjftjia2w46s"]'
code-review-bot --conf=~/dev/mozilla/conf-dev.yml …
```

Update RevisionBuild state to provide required data to Lando

---

bot/code_review_bot/cli.py
bot/code_review_bot/config.py
bot/code_review_bot/revisions.py
bot/code_review_bot/workflow.py
bot/tests/mocks/phabricator_revision_search.json
bot/tests/test_analysis.py

This PR is needed to support the new payload that will be sent by Phabricatior's Harbormaster build step using https://github.com/mozilla-conduit/phabricator/pull/49
This simplifies a lot the `Revision` setup as we will directly use a Phabricator build target directly linked to a Diff & Revision. So there is no need to "guess" the diff from transactions and fallback to the last diff.

Depend on Phabricator build target ID in trigger mode

---

.taskcluster.yml
backend/requirements.txt
integration/requirements.txt

The `code_review_tools` sub-project is now only necessary in the events codebase.
This MR removes:
- tools requirement in the backend: there were no more usage of the lib in the code base
- installation in CI for:
- bot unit tests
- backend unit tests
- integration hook unit tests
Next step are to remove events CI, then events & tools codebase

Remove code_review_tools from CI usage

---

backend/code_review_backend/issues/api.py

I found another bug due to the Repository list being almost empty on testing backend (`mozilla-central` was missing).
So when the bot requests a list of existing issues for the repo, it triggered a 500 ([exception in the bot here](https://firefox-ci-tc.services.mozilla.com/tasks/BbdEDHrQRPSxJPXx2-aqYg/runs/0/logs/live/public/logs/live.log))
The `repo` value was not initialized when no `Repository` was found, leading to the crash.
Now the API returns a proper 400 when there are no matching repo, and the testing instance returns an empty list as I created the `mozilla-central` repo in the admin

Fix repo early usage in the backend new endpoints

---

bot/docker/Dockerfile
tools/docker/bootstrap-mercurial.sh

That previous PR #2628 silently broke the symlink towards our `hgrc`.
the `hg robustcheckout` extension was missing in the docker image (example [failure on testing](https://firefox-ci-tc.services.mozilla.com/tasks/HNmNu_OtQdyK03wAl-ivLw/runs/0/logs/public/logs/live.log))
I fixed the paths & docker build, and added a check in the bash script to prevent this from happening again.

Fix hgrc in bot Docker image

---

bot/code_review_bot/config.py
bot/code_review_bot/workflow.py
bot/tests/test_workflow.py

This publishes 2 more links on the Harbormaster build, towards both Taskcluster tasks (analysis & publication stages).

Publish task links for analysis & publication workflows

---

.taskcluster.yml

This simplify Taskcluster CI tasks by removing unit tests and build steps, along with events deployment.

Remove events from CI

---

bot/code_review_bot/__init__.py
bot/code_review_bot/cli.py
bot/code_review_bot/config.py
bot/code_review_bot/revisions.py
bot/code_review_bot/workflow.py

Refs #2773
This PR replaces usage of `MOZILLA_CENTRAL_TASK_GROUP_ID` and `AUTOLAND_TASK_GROUP_ID` by `GENERIC_TASK_GROUP_ID`.
The existing code already [looks up the head repository](https://github.com/mozilla/code-review/blob/master/bot/code_review_bot/revisions.py#L291-L314) and is generic, supporting both Autoland & MC.
This assumes that the hook is triggered directly with a unique `GENERIC_TASK_GROUP_ID` environment variable.

Use a generic env variable instead of MC/Autoland ones

---

.taskcluster.yml
bot/code_review_bot/mercurial.py
bot/code_review_bot/workflow.py
bot/requirements-dev.txt
bot/tests/conftest.py
bot/tests/mocks/phabricator_edges-PHID-DREV-666.json
bot/tests/mocks/phabricator_edges-PHID-DREV-badutf8.json
bot/tests/mocks/phabricator_edges-PHID-DREV-deadbeef.json
bot/tests/mocks/phabricator_edges-PHID-DREV-deadbeefParent.json
bot/tests/mocks/phabricator_edges-PHID-DREV-solo.json
bot/tests/mocks/phabricator_projects.json
bot/tests/mocks/phabricator_raw-1233.json
bot/tests/mocks/phabricator_raw-1234.json
bot/tests/mocks/phabricator_raw-555.json
bot/tests/mocks/phabricator_raw-666.json
bot/tests/mocks/phabricator_raw-9876.json
bot/tests/mocks/phabricator_repositories.json
bot/tests/mocks/phabricator_search-PHID-DIFF-666.json
bot/tests/mocks/phabricator_search-PHID-DIFF-badutf8.json
bot/tests/mocks/phabricator_search-PHID-DIFF-solo.json
bot/tests/mocks/phabricator_search-PHID-DIFF-test123.json
bot/tests/mocks/phabricator_search-PHID-DIFF-xxxx.json
bot/tests/mocks/phabricator_search-PHID-DREV-deadbeefParent.json
bot/tests/test_analysis.py
bot/tests/test_mercurial.py

Refs #2827 
This is a rather large chunk of code to import, and even larger when considering the extensive test suite and its fixtures.
I simplified the imported codebase to:
- replace async methods by synchronous (no need anymore to be async)
- remove the bus messaging part (not needed as we directly call the method and expect a single result)
- remove multiple repositories management from `MercurialWorker` as we only need the one from task that is already cloned
I found a small issue in the current `master` implementation: as we call `handle_build` directly, there is no retry on specific errors (due to try being down or rejecting the payload). The test suite identified that missing case easily and I added it back.

Import libmozevent mercurial

---

bot/code_review_bot/cli.py
bot/code_review_bot/config.py
bot/code_review_bot/mercurial.py

Closes #2882
Follow up of #2861, required to deploy on testing.

Use secret for github API token

---

bot/code_review_bot/mercurial.py

Essentially reverts https://github.com/mozilla/libmozevent/commit/464816691a9f28a49c84935c7d3d4097536fb060
Fixes #2899

Remove the `hg up null` workaround as it is no longer needed

---

backend/ci/setup_postgres.sh

This solves the CI latest issue due to `python:3.12` base Debian docker image being updated

Use postgres 17 in CI for backend tests

---

bot/code_review_bot/mercurial.py
bot/tests/conftest.py
bot/tests/test_analysis.py
bot/tests/test_mercurial.py

Ref. https://github.com/mozilla/code-review/issues/2887
The hglib client only supports the similarity parameter (and not the `config` option): https://repo.mercurial-scm.org/python-hglib/file/tip/hglib/client.py#l959. Therefore, I could not implement the fall back command in case the command fails. It should be possible with a raw call to `hg`, but I suppose we want to avoid that.
I did not added the `--no-commit` option as Bastien told me it would work only on try.

Apply patches from Phabricator in a smarter way

---

.taskcluster.yml

We don't use docker-in-docker anymore.

Don't request the `dind` docker-worker feature

---

bot/code_review_bot/tasks/tgdiff.py
bot/tests/test_tgdiff_task.py

The taskgraph-reviewers group isn't meant to review thunderbird changes.

tgdiff: only add taskgraph-reviewers for gecko patches

---

bot/code_review_bot/workflow.py

Closes #2811 
While looking into #2972 I found that part of the issue could come from #2811
It's now easy to do since we onboarded the libmozevent mercurial code in #2842

Use revision base changeset as repo starting point for patches

---

bot/code_review_bot/workflow.py

Reverts mozilla/code-review#2983

Revert "Use revision base changeset as repo starting point for patches"
